# Run actions for only changed files. Customizable for any language and action. Code below is an example for Flake8 on Python.

name: changed-file-action

on: push

jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade flake8
    - name: Get Changed Files
      id: get_file_changes
      uses: dorner/file-changes-action@v1.2.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        plaintext: true
    - name: RESULTS
      run: |
        for directory in ${{ steps.get_file_changes.outputs.files }}
        do
          if [ ${directory: -3} == ".py" ]
          then
            echo Test conducted on $directory
            flake8 $directory
          fi
        done

